 const dummyBuyers = [
  { name: 'Javed', city: 'Dhaka' },
  { name: 'Rahim', city: 'Chittagong' },
  { name: 'Karim', city: 'Sylhet' },
  { name: 'Sajid', city: 'Khulna' },
  { name: 'Imran', city: 'Rajshahi' },
  { name: 'Hasan', city: 'Barisal' },
  { name: 'Rafi', city: 'Cumilla' },
  { name: 'Nayeem', city: 'Narayanganj' },
  { name: 'Fahim', city: 'Gazipur' },
  { name: 'Arif', city: 'Mymensingh' },

  { name: 'Sabbir', city: 'Dhaka' },
  { name: 'Tanvir', city: 'Chittagong' },
  { name: 'Mahin', city: 'Sylhet' },
  { name: 'Arafat', city: 'Khulna' },
  { name: 'Siam', city: 'Rajshahi' },
  { name: 'Shanto', city: 'Barisal' },
  { name: 'Rashed', city: 'Cumilla' },
  { name: 'Nabil', city: 'Narayanganj' },
  { name: 'Ashik', city: 'Gazipur' },
  { name: 'Hridoy', city: 'Mymensingh' },

  { name: 'Riyad', city: 'Dhaka' },
  { name: 'Tarek', city: 'Chittagong' },
  { name: 'Foysal', city: 'Sylhet' },
  { name: 'Sohag', city: 'Khulna' },
  { name: 'Rubel', city: 'Rajshahi' },
  { name: 'Badhon', city: 'Barisal' },
  { name: 'Munna', city: 'Cumilla' },
  { name: 'Shakil', city: 'Narayanganj' },
  { name: 'Sumon', city: 'Gazipur' },
  { name: 'Jony', city: 'Mymensingh' },

  { name: 'Farhan', city: 'Dhaka' },
  { name: 'Saif', city: 'Chittagong' },
  { name: 'Tahsin', city: 'Sylhet' },
  { name: 'Anik', city: 'Khulna' },
  { name: 'Mehedi', city: 'Rajshahi' },
  { name: 'Parvez', city: 'Barisal' },
  { name: 'Rana', city: 'Cumilla' },
  { name: 'Kawsar', city: 'Narayanganj' },
  { name: 'Noman', city: 'Gazipur' },
  { name: 'Shuvo', city: 'Mymensingh' },

  { name: 'Akash', city: 'Dhaka' },
  { name: 'Nazmul', city: 'Chittagong' },
  { name: 'Mamun', city: 'Sylhet' },
  { name: 'Ruhul', city: 'Khulna' },
  { name: 'Alamin', city: 'Rajshahi' },
  { name: 'Sakib', city: 'Barisal' },
  { name: 'Riaz', city: 'Cumilla' },
  { name: 'Masud', city: 'Narayanganj' },
  { name: 'Selim', city: 'Gazipur' },
  { name: 'Belal', city: 'Mymensingh' },

  { name: 'Mahmud', city: 'Dhaka' },
  { name: 'Asif', city: 'Chittagong' },
  { name: 'Jubayer', city: 'Sylhet' },
  { name: 'Omar', city: 'Khulna' },
  { name: 'Aminul', city: 'Rajshahi' },
  { name: 'Touhid', city: 'Barisal' },
  { name: 'Rifat', city: 'Cumilla' },
  { name: 'Shahin', city: 'Narayanganj' },
  { name: 'Iqbal', city: 'Gazipur' },
  { name: 'Habib', city: 'Mymensingh' },

  { name: 'Nizam', city: 'Dhaka' },
  { name: 'Saiful', city: 'Chittagong' },
  { name: 'Rasel', city: 'Sylhet' },
  { name: 'Mizan', city: 'Khulna' },
  { name: 'Shahadat', city: 'Rajshahi' },
  { name: 'Biplob', city: 'Barisal' },
  { name: 'Ehsan', city: 'Cumilla' },
  { name: 'Tushar', city: 'Narayanganj' },
  { name: 'Yasin', city: 'Gazipur' },
  { name: 'Adnan', city: 'Mymensingh' },
]


export default dummyBuyers